name: 'coverage'
permissions:
  pull-requests: write
on:
    pull_request:
        branches:
            - main
    push:
      branches:
        - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
